Repository singnet/das, pull requests merged in 2025-03, with the labels that each got.

#290 [#289] fixing AttentionBrokerUpdater thread
  src/query_engine/answer_processor/AttentionBrokerUpdater.h
Labels: ReviewerCanMergeIt

#293 [#125][round 1] Deleting thread objects
  src/attention_broker/WorkerThreads.cc
  src/distributed_algorithm_node/MessageBroker.cc
  src/query_engine/QueryNode.cc
  src/query_engine/query_element/And.h
  src/query_engine/query_element/LinkTemplate.h
  src/query_engine/query_element/Or.h
  src/query_engine/query_element/RemoteSink.cc
Labels: ReviewerCanMergeIt

#294 [#125] Adding Memory Pool
  src/commons/MemoryPool.h
  src/query_engine/DASNode.cc
  src/query_engine/DASNode.h
  src/query_engine/query_element/And.h
  src/query_engine/query_element/LinkTemplate.h
  src/query_engine/query_element/Operator.h
  src/query_engine/query_element/Or.h
  src/query_engine/query_element/QueryElement.h
  src/query_engine/query_element/Terminal.h
Labels: ReviewerCanMergeIt

#306 [#305] Skip star_node test
  src/tests/python/unit/BUILD
Labels: bug

#331 [#330] small improvements on Makefile and test
  Makefile
  src/scripts/bazel.sh
  src/tests/cpp/remote_sink_iterator_test.cc
Labels: ReviewerCanMergeIt

#342 [HOTFIX] Fix bad use of freed QueryAnswer by AttentionBrokerUpdater
  src/query_engine/answer_processor/AttentionBrokerUpdater.h
  src/query_engine/query_element/And.h
Labels: ReviewerCanMergeIt

#340 [Fix] Add `update_attention_broker` to query client
  src/main/query_client_main.cc
Labels: bug, enhancement

#345 [HOTFIX] Implements test cases of PM queries updating the attention broker
  src/tests/cpp/das_node_test.cc
Labels: ReviewerCanMergeIt
